export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
    RESET_REQUEST: "RESET_REQUEST",
    RESET_SUCCESS: "RESET_SUCCESS",
    RESET_FAILURE: "RESET_FAILURE",
};

export const initialDataConstants = {
  GET_ALL_INITIAL_DATA_REQUEST: "GET_ALL_INITIAL_DATA_REQUEST",
  GET_ALL_INITIAL_DATA_SUCCESS: "GET_ALL_INITIAL_DATA_SUCCESS",
  GET_ALL_INITIAL_DATA_FAILURE: "GET_ALL_INITIAL_DATA_FAILURE",
};

export const slotConstants = {
  GET_SLOTS_REQUEST: "GET_SLOTS_REQUEST",
  GET_SLOTS_SUCCESS: "GET_SLOTS_SUCCESS",
  GET_SLOTS_FAILURE: "GET_SLOTS_FAILURE",
  CREATE_SLOTS_REQUEST: "CREATE_SLOTS_REQUEST",
  CREATE_SLOTS_SUCCESS: "CREATE_SLOTS_SUCCESS",
  CREATE_SLOTS_FAILURE: "CREATE_SLOTS_FAILURE",
  DELETE_SLOT_REQUEST: "DELETE_SLOT_REQUEST",
  DELETE_SLOT_SUCCESS: "DELETE_SLOT_SUCCESS",
  DELETE_SLOT_FAILURE: "DELETE_SLOT_FAILURE",
};

export const specialisationConstants = {
  GET_SPECIALISATION_REQUEST: "GET_SPECIALISATION_REQUEST",
  GET_SPECIALISATION_SUCCESS: "GET_SPECIALISATION_SUCCESS",
  GET_SPECIALISATION_FAILURE: "GET_SPECIALISATION_FAILURE",
  CREATE_SPECIALISATION_REQUEST: "CREATE_SPECIALISATION_REQUEST",
  CREATE_SPECIALISATION_SUCCESS: "CREATE_SPECIALISATION_SUCCESS",
  CREATE_SPECIALISATION_FAILURE: "CREATE_SPECIALISATION_FAILURE",
  DELETE_SPECIALISATION_REQUEST: "DELETE_SPECIALISATION_REQUEST",
  DELETE_SPECIALISATION_SUCCESS: "DELETE_SPECIALISATION_SUCCESS",
  DELETE_SPECIALISATION_FAILURE: "DELETE_SPECIALISATION_FAILURE",
};

export const priceConstants = {
  GET_PRICE_REQUEST: "GET_PRICE_REQUEST",
  GET_PRICE_SUCCESS: "GET_PRICE_SUCCESS",
  GET_PRICE_FAILURE: "GET_PRICE_FAILURE",
  CHANGE_PRICE_REQUEST: "CHANGE_PRICE_REQUEST",
  CHANGE_PRICE_SUCCESS: "CHANGE_PRICE_SUCCESS",
  CHANGE_PRICE_FAILURE: "CHANGE_PRICE_FAILURE",
};

export const locationConstants = {
  GET_LOCATION_REQUEST: "GET_LOCATION_REQUEST",
  GET_LOCATION_SUCCESS: "GET_LOCATION_SUCCESS",
  GET_LOCATION_FAILURE: "GET_LOCATION_FAILURE",
  CREATE_LOCATION_REQUEST: "CREATE_LOCATION_REQUEST",
  CREATE_LOCATION_SUCCESS: "CREATE_LOCATION_SUCCESS",
  CREATE_LOCATION_FAILURE: "CREATE_LOCATION_FAILURE",
  DELETE_LOCATION_REQUEST: "DELETE_LOCATION_REQUEST",
  DELETE_LOCATION_SUCCESS: "DELETE_LOCATION_SUCCESS",
  DELETE_LOCATION_FAILURE: "DELETE_LOCATION_FAILURE",
};